### ISSUE TITLE
Suggested Enhancement

### ISSUE THREAD

**Issue by andrewhenke** [Lakshkhandelwal/Host-Header-Injection-Testing#1]
Hello! Nice project you've got here, I am actually looking to claim some high-value bug bounties and your tools are (hopefully) going to help me get the proof I need to claim my reward! 

I would just like to recommend that instead of telling your users what the dependencies are in the `README.md` you might just create a `requirements.txt` file so that when a user downloads or clones your repository, all they need to do to install is run the command `sudo pip install -r requirements.txt` 

This might make it significantly easier and more professional if you utilize this tool, as I'm sure you've seen before! :)  Keep up the good work!

**Comment by Lakshkhandelwal** [comment]
Hello,
I have now updated the repository with a requirements.txt file.
Thank you for providing the feedback.
I hope you got your bounties !!
